[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[workspace]
members = [
    "programs/absolute-vault",
    "programs/smart-dial"
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"