[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
absolute_vault = "355Ey2cQSCMmBRSnbKSQJfvCcXzzyCC3eC1nGTyeaFXt"
smart_dial = "KNKv3pAEiA313iGTSWUZ9yLF5pPDSCpDKb3KLJ9ibPA"

[programs.devnet]
absolute_vault = "355Ey2cQSCMmBRSnbKSQJfvCcXzzyCC3eC1nGTyeaFXt"
smart_dial = "KNKv3pAEiA313iGTSWUZ9yLF5pPDSCpDKb3KLJ9ibPA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deployer-test.json"

[scripts]
test = "nx run anchor:test --skip-lint"