[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
absolute_vault = "AbsV1111111111111111111111111111111111111111"
smart_dial = "Dia11111111111111111111111111111111111111111"

[programs.devnet]
absolute_vault = "AbsV1111111111111111111111111111111111111111"
smart_dial = "Dia11111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"