services:
  phase1-programs:
    build:
      context: ./docker/phase1-programs
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: miko-phase1-programs
    volumes:
      - ./docker/shared-artifacts:/shared-artifacts
      - ./programs:/workspace/programs
    environment:
      - SOLANA_NETWORK=devnet
      - RUST_LOG=info
    working_dir: /workspace
    command: tail -f /dev/null
    networks:
      - miko-network

  phase2-token:
    build:
      context: ./docker/phase2-token
      dockerfile: Dockerfile
    container_name: miko-phase2-token
    volumes:
      - ./docker/shared-artifacts:/shared-artifacts
      - ./scripts:/workspace/scripts
    environment:
      - SOLANA_NETWORK=devnet
    working_dir: /workspace
    command: tail -f /dev/null
    depends_on:
      - phase1-programs
    networks:
      - miko-network

  phase3-init:
    build:
      context: ./docker/phase3-init
      dockerfile: Dockerfile
    container_name: miko-phase3-init
    volumes:
      - ./docker/shared-artifacts:/shared-artifacts
      - ./scripts:/workspace/scripts
    environment:
      - SOLANA_NETWORK=devnet
    working_dir: /workspace
    command: tail -f /dev/null
    depends_on:
      - phase2-token
    networks:
      - miko-network

  phase4-keeper:
    build:
      context: ./docker/phase4-keeper
      dockerfile: Dockerfile
    container_name: miko-phase4-keeper
    volumes:
      - ./docker/shared-artifacts:/shared-artifacts
      - ./keeper-bot:/workspace/keeper-bot
    environment:
      - NODE_ENV=production
      - SOLANA_NETWORK=devnet
    working_dir: /workspace
    command: tail -f /dev/null
    depends_on:
      - phase3-init
    networks:
      - miko-network

networks:
  miko-network:
    driver: bridge

volumes:
  shared-artifacts:
    driver: local