version: '3.8'

services:
  phase1-programs:
    build:
      context: ./docker/phase1-programs
      dockerfile: Dockerfile
    container_name: miko-phase1-programs
    volumes:
      - ./docker/shared-artifacts:/shared-artifacts
      - ./programs:/workspace/programs
    environment:
      - RUST_LOG=info
      - ANCHOR_PROVIDER_URL=https://api.devnet.solana.com
    networks:
      - miko-network
    stdin_open: true
    tty: true
    command: /bin/bash

  phase2-token:
    build:
      context: ./docker/phase2-token
      dockerfile: Dockerfile
    container_name: miko-phase2-token
    volumes:
      - ./docker/shared-artifacts:/shared-artifacts
      - ./scripts:/workspace/scripts
    environment:
      - SOLANA_RPC_URL=https://api.devnet.solana.com
    networks:
      - miko-network
    depends_on:
      - phase1-programs
    stdin_open: true
    tty: true
    command: /bin/bash

  phase3-init:
    build:
      context: ./docker/phase3-init
      dockerfile: Dockerfile
    container_name: miko-phase3-init
    volumes:
      - ./docker/shared-artifacts:/shared-artifacts
      - ./scripts:/workspace/scripts
    environment:
      - SOLANA_RPC_URL=https://api.devnet.solana.com
    networks:
      - miko-network
    depends_on:
      - phase2-token
    stdin_open: true
    tty: true
    command: /bin/bash

  phase4-keeper:
    build:
      context: .
      dockerfile: ./docker/phase4-keeper/Dockerfile
    container_name: miko-phase4-keeper
    volumes:
      - ./docker/shared-artifacts:/shared-artifacts
      - ./keeper-bot:/workspace/keeper-bot
      - ./keeper-bot/logs:/workspace/keeper-bot/logs
    environment:
      - NODE_ENV=development
      - SOLANA_RPC_URL=https://api.devnet.solana.com
      - CONFIG_PATH=/workspace/keeper-bot/config/mock_config.toml
    networks:
      - miko-network
    depends_on:
      - phase3-init
    stdin_open: true
    tty: true
    command: /bin/bash

networks:
  miko-network:
    driver: bridge

volumes:
  shared-artifacts:
    driver: local