[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
absolute_vault = "4ieMsf7qFmh1W5FwcaX6M3fz3NNyaGy3FyuXoKJLrRDq"
smart_dial = "DggkQFbBnkMCK43y5JTHfYdX3CKw2H3m177TbLC7Mjdz"
transfer_hook = "4E8NzqDaN76o7zXjLo8hYetmiBKmAXPs6vUMFaqFfmg4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --max-old-space-size=8192 node_modules/@coral-xyz/anchor/dist/cjs/cli/cli.js test"
