[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
smart-dial = "2Ymuq9Nt9s1GH1qGVuFd6jCqefJcmsPReE3MmiieEhZc"
transfer-hook = "2Mh6sSYeqeyqRZz8cr7y8gFtxyNf7HoMWqwzm9uTFav3"
absolute-vault = "5hVLxMW58Vaax1kWt9Xme3AoS5ZwUfGaCi34eDiaFAzu"

[programs.devnet]
smart-dial = "2Ymuq9Nt9s1GH1qGVuFd6jCqefJcmsPReE3MmiieEhZc"
transfer-hook = "2Mh6sSYeqeyqRZz8cr7y8gFtxyNf7HoMWqwzm9uTFav3"
absolute-vault = "5hVLxMW58Vaax1kWt9Xme3AoS5ZwUfGaCi34eDiaFAzu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
