# MIKO Keeper Bot Mock Configuration
# Phase 4-A: Mock CI Tests

[network]
# Mock RPC endpoints for testing
rpc_primary = "https://api.devnet.solana.com"
rpc_backup = "https://api.devnet.solana.com"
network_type = "devnet"
commitment = "confirmed"

[programs]
# Program IDs from shared-artifacts
vault_program_id = "4ieMsf7qFmh1W5FwcaX6M3fz3NNyaGy3FyuXoKJLrRDq"
smart_dial_program_id = "DggkQFbBnkMCK43y5JTHfYdX3CKw2H3m177TbLC7Mjdz"
token_program_id = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[token]
# MIKO token mint from Phase 2
mint_address = "A9xZnPo2SvSgWiSxh4XApZyjyYRcH1ES8zTCvhzogYRE"
decimals = 9
total_supply = 1000000000

[keeper]
# Test keeper wallet (no real funds)
wallet_pubkey = "5E8kjrFSVugkU9tv378uEYQ78DNp9z2MLY2fjSU5E3Ju"
min_sol_balance = 0.05
max_sol_balance = 0.10

[harvest]
# Harvest threshold: 500,000 MIKO (0.05% of supply)
threshold_miko = 500000
batch_size = 20
retry_attempts = 3
retry_delay_ms = 1000

[adapters]
# Mock adapter configurations
raydium = "MockRaydiumAdapter"
jupiter = "MockJupiterAdapter"
birdeye = "MockBirdeyeAdapter"

[test_data]
# Test launch timestamp (Unix timestamp)
launch_timestamp = 1737388800  # Monday, January 20, 2025 00:00:00 UTC
keeper_balance = 0.05
mock_holder_count = 100
mock_price_usd = 0.001
mock_24h_volume = 1000000

[apis]
# Mock API configurations
[apis.twitter]
enabled = false
api_key = "mock_twitter_key"
api_secret = "mock_twitter_secret"
access_token = "mock_access_token"
access_secret = "mock_access_secret"
account_handle = "project_miko"

[apis.birdeye]
enabled = false
api_key = "mock_birdeye_key"
base_url = "http://localhost:3001/mock-birdeye"

[apis.jupiter]
enabled = false
base_url = "http://localhost:3002/mock-jupiter"
slippage_bps = 100  # 1%

[timing]
# Schedule configurations
fee_update_5min = 300    # 5 minutes in seconds
fee_update_10min = 600   # 10 minutes in seconds
harvest_check_interval = 60  # Check every minute
monday_check_time = "03:00:00"  # UTC

[logging]
level = "debug"
file = "keeper-bot.log"
max_size_mb = 100
max_files = 5